[[drone]]
id = 1
connected_node_ids = [2, 3, 200]
pdr = 0.00

[[drone]]
id = 2
connected_node_ids = [1, 4, 100]
pdr = 0.00

[[drone]]
id = 3
connected_node_ids = [1, 4, 5, 200]
pdr = 0.00

[[drone]]
id = 4
connected_node_ids = [2, 3, 6]
pdr = 0.00

[[drone]]
id = 5
connected_node_ids = [3, 6, 7]
pdr = 0.00

[[drone]]
id = 6
connected_node_ids = [4, 5, 8, 201]
pdr = 0.00

[[drone]]
id = 7
connected_node_ids = [5, 8, 9, 101]
pdr = 0.00

[[drone]]
id = 8
connected_node_ids = [6, 7, 10, 201]
pdr = 0.00

[[drone]]
id = 9
connected_node_ids = [7, 10]
pdr = 0.00

[[drone]]
id = 10 
connected_node_ids = [8, 9]
pdr = 0.00

[[client]]
id = 100
connected_drone_ids = [2]

[[client]]
id = 101
connected_drone_ids = [7]

[[server]]
id = 200
connected_drone_ids = [1, 3]

[[server]]
id = 201
connected_drone_ids = [6, 8]

