[[drone]]
id = 1
connected_node_ids = [2, 10, 20]
pdr = 0.00

[[drone]]
id = 2
connected_node_ids = [1, 3, 11, 20, 21]
pdr = 0.00

[[drone]]
id = 3
connected_node_ids = [2, 4, 12, 20, 21]
pdr = 0.00

[[drone]]
id = 4
connected_node_ids = [3, 13, 21]
pdr = 0.00

[[client]]
id = 10
connected_drone_ids = [1]

[[client]]
id = 11
connected_drone_ids = [2]

[[client]]
id = 12
connected_drone_ids = [3]

[[client]]
id = 13
connected_drone_ids = [4]

[[server]]
id = 20
connected_drone_ids = [1, 2, 3]

[[server]]
id = 21
connected_drone_ids = [2, 3, 4]
