# Sub-Net Forms: Two Five-Pointed Stars
# Two sub-networks of 5 drones each forming five-pointed stars
# Star 1: drones 1-5, Star 2: drones 6-10
# Each star has internal connections (2nd follower) + inter-subnet connections

# First Five-Pointed Star (Sub-network 1)
[[drone]]
id = 1
connected_node_ids = [3, 4, 6]  # 2nd follower + inter-subnet
pdr = 0.10

[[drone]]
id = 2
connected_node_ids = [4, 5, 7]  # 2nd follower + inter-subnet
pdr = 0.15

[[drone]]
id = 3
connected_node_ids = [5, 1, 11]  # 2nd follower in star
pdr = 0.20

[[drone]]
id = 4
connected_node_ids = [1, 2]  # 2nd follower in star
pdr = 0.12

[[drone]]
id = 5
connected_node_ids = [2, 3, 13]  # 2nd follower in star
pdr = 0.18

# Second Five-Pointed Star (Sub-network 2)
[[drone]]
id = 6
connected_node_ids = [8, 9, 1]  # 2nd follower + inter-subnet
pdr = 0.25

[[drone]]
id = 7
connected_node_ids = [9, 10, 2]  # 2nd follower + inter-subnet
pdr = 0.08

[[drone]]
id = 8
connected_node_ids = [10, 6, 12]  # 2nd follower in star
pdr = 0.14

[[drone]]
id = 9
connected_node_ids = [6, 7, 13]  # 2nd follower in star
pdr = 0.16

[[drone]]
id = 10
connected_node_ids = [7, 8, 12]  # 2nd follower in star
pdr = 0.11

[[client]]
id = 11
connected_drone_ids = [3]

[[client]]
id = 12
connected_drone_ids = [8, 10]

[[server]]
id = 13
connected_drone_ids = [5, 9]