# Star (Decagram) Topology
# 10 drones arranged in a circle, each connected to its 3rd follower
# Circle order: 1-2-3-4-5-6-7-8-9-10
# Each drone connects to the drone 3 positions ahead (wrapping around)

[[drone]]
id = 1
connected_node_ids = [4, 8, 11]
pdr = 0.10

[[drone]]
id = 2
connected_node_ids = [5, 9, 12]
pdr = 0.15

[[drone]]
id = 3
connected_node_ids = [6, 10, 12]
pdr = 0.20

[[drone]]
id = 4
connected_node_ids = [7, 1]
pdr = 0.12

[[drone]]
id = 5
connected_node_ids = [8, 2]
pdr = 0.18

[[drone]]
id = 6
connected_node_ids = [9, 3]
pdr = 0.25

[[drone]]
id = 7
connected_node_ids = [10, 4]
pdr = 0.08

[[drone]]
id = 8
connected_node_ids = [1, 5, 13]
pdr = 0.14

[[drone]]
id = 9
connected_node_ids = [2, 6, 13]
pdr = 0.16

[[drone]]
id = 10
connected_node_ids = [3, 7]
pdr = 0.11

[[client]]
id = 11
connected_drone_ids = [1]

[[client]]
id = 12
connected_drone_ids = [2, 3]

[[server]]
id = 13
connected_drone_ids = [8, 9]