[[drone]]
id = 1
connected_node_ids = [2, 10, 20, 21]
pdr = 0.00

[[drone]]
id = 2
connected_node_ids = [1, 11, 20, 21]
pdr = 0.00

[[client]]
id = 10
connected_drone_ids = [1]

[[client]]
id = 11
connected_drone_ids = [2]

[[server]]
id = 20
connected_drone_ids = [1, 2]

[[server]]
id = 21
connected_drone_ids = [1, 2]
