# Sub-Net Forms: Two Triangles and One Square
# Triangle 1: drones 1-3, Triangle 2: drones 4-6, Square: drones 7-10
# Each sub-network has internal connections + inter-subnet connections

# First Triangle (Sub-network 1)
[[drone]]
id = 1
connected_node_ids = [2, 3, 4, 13]  # Triangle connections + inter-subnet to Triangle 2
pdr = 0.10

[[drone]]
id = 2
connected_node_ids = [1, 3, 5]  # Triangle connections + inter-subnet to Triangle 2
pdr = 0.15

[[drone]]
id = 3
connected_node_ids = [1, 2, 11]  # Triangle connections only
pdr = 0.20

# Second Triangle (Sub-network 2)
[[drone]]
id = 4
connected_node_ids = [5, 6, 1, 7]  # Triangle connections + inter-subnet to Triangle 1 and Square
pdr = 0.12

[[drone]]
id = 5
connected_node_ids = [4, 6, 2, 8]  # Triangle connections + inter-subnet to Triangle 1 and Square
pdr = 0.18

[[drone]]
id = 6
connected_node_ids = [4, 5, 12]  # Triangle connections only
pdr = 0.25

# Square (Sub-network 3)
[[drone]]
id = 7
connected_node_ids = [8, 10, 4, 9]  # Square connections + inter-subnet to Triangle 2
pdr = 0.08

[[drone]]
id = 8
connected_node_ids = [7, 9, 5, 10]  # Square connections + inter-subnet to Triangle 2
pdr = 0.14

[[drone]]
id = 9
connected_node_ids = [8, 10, 7, 12]  # Square connections only
pdr = 0.16

[[drone]]
id = 10
connected_node_ids = [7, 9, 8, 13]  # Square connections only
pdr = 0.11

[[client]]
id = 11
connected_drone_ids = [3]

[[client]]
id = 12
connected_drone_ids = [6, 9]

[[server]]
id = 13
connected_drone_ids = [1, 10]