# Butterfly Topology
# Based on FFT circuit design with 10 nodes
# Structure with crossing connections forming butterfly pattern
# Top layer: 1,2,3,4
# Middle layer: 5,6,7,8
# Bottom layer: 9,10

[[drone]]
id = 1
connected_node_ids = [5, 6, 11]
pdr = 0.10

[[drone]]
id = 2
connected_node_ids = [5, 6, 12]
pdr = 0.15

[[drone]]
id = 3
connected_node_ids = [7, 8]
pdr = 0.20

[[drone]]
id = 4
connected_node_ids = [7, 8, 12]
pdr = 0.12

[[drone]]
id = 5
connected_node_ids = [1, 2, 9]
pdr = 0.18

[[drone]]
id = 6
connected_node_ids = [1, 2, 10]
pdr = 0.25

[[drone]]
id = 7
connected_node_ids = [3, 4, 9]
pdr = 0.08

[[drone]]
id = 8
connected_node_ids = [3, 4, 10]
pdr = 0.14

[[drone]]
id = 9
connected_node_ids = [5, 7, 10, 13]
pdr = 0.16

[[drone]]
id = 10
connected_node_ids = [6, 8, 9, 13]
pdr = 0.11

[[client]]
id = 11
connected_drone_ids = [1]

[[client]]
id = 12
connected_drone_ids = [2, 4]

[[server]]
id = 13
connected_drone_ids = [9, 10]