# Double Chain Topology
# Two lines of 5 drones each, connected horizontally and vertically
# Top line: 1-2-3-4-5
# Bottom line: 6-7-8-9-10
# Vertical connections: 1-6, 2-7, 3-8, 4-9, 5-10

[[drone]]
id = 1
connected_node_ids = [2, 6, 11]
pdr = 0.10

[[drone]]
id = 2
connected_node_ids = [1, 3, 7]
pdr = 0.15

[[drone]]
id = 3
connected_node_ids = [2, 4, 8]
pdr = 0.20

[[drone]]
id = 4
connected_node_ids = [3, 5, 9]
pdr = 0.10

[[drone]]
id = 5
connected_node_ids = [4, 10, 13]
pdr = 0.05

[[drone]]
id = 6
connected_node_ids = [1, 7, 12]
pdr = 0.12

[[drone]]
id = 7
connected_node_ids = [6, 8, 2, 12]
pdr = 0.18

[[drone]]
id = 8
connected_node_ids = [7, 9, 3]
pdr = 0.22

[[drone]]
id = 9
connected_node_ids = [8, 10, 4]
pdr = 0.08

[[drone]]
id = 10
connected_node_ids = [9, 5, 13]
pdr = 0.14

[[client]]
id = 11
connected_drone_ids = [1]

[[client]]
id = 12
connected_drone_ids = [6, 7]

[[server]]
id = 13
connected_drone_ids = [5, 10]