name: Test Suite

on:
  push:
    branches:
      - '**' # Run on all branches
  pull_request:
    branches:
      - '**' # Run on all PRs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable # Use the stable Rust toolchain

      - name: Run tests
        run: |
          cargo test --workspace || echo "No tests found or tests failed"
